Repository WeBeginners-Community/DocBook, pull requests merged in 2023-01, with the labels that each got.

#27 Doc 23 bubble sort doc
  Algorithms/Bubble Sort/bubble-sort.md
Labels: Beginner, SWOC 2023

#28 Doc 25 insertion sort doc
  Algorithms/Insertion Sort/insertion-sort.md
Labels: Beginner, SWOC 2023

#42 create radix.md
  Algorithms/Radix Sort/radix.md
Labels: Beginner, SWOC 2023

#38 Create GCD and LCM.md
  C++/Recursion/GCD and LCM.md
Labels: Beginner, SWOC 2023

#54 Added Heap Sort
  Algorithms/Heap Sort/heap-sort.md
Labels: Beginner, SWOC 2023

#61 Doc for hashing theory
  Algorithms/Hashing/hashing.md
Labels: Beginner, SWOC 2023

#56 Binary Search Using Recursion Added
  C++/Recursion/BInary Search.md
Labels: Beginner, SWOC 2023

#77 Added Counting sort documentation
  Algorithms/Counting Sort/README.md
Labels: Beginner, SWOC 2023

#70 Created Counting Sort.md in Algorithms
  Algorithms/Counting Sort/counting-sort.md
Labels: Beginner, SWOC 2023

#93 Iterations in C++ added
  C++/C++ Basics/Iterations in CPP.md
Labels: Beginner, SWOC 2023

#94 Doc #45 heap sort
  Algorithms/Heap Sort/heap-sort.md
Labels: Beginner, SWOC 2023

#102 Create Node-js Documentation.md
  NodeJs/Node-js Documentation.md
Labels: Beginner, SWOC 2023

#103 Fibonacci Series using recursion added
  C++/Recursion/Fibonacci Series.md
Labels: Beginner, SWOC 2023

#100 added Merge sort algorithm
  Algorithms/Merge Sort/README.md
Labels: Beginner, SWOC 2023

#98 Added python documentation
  Python/Introduction.md
Labels: Beginner, SWOC 2023

#104 added Bitwise and operator
  C++/Bitwise Operator/bitwise-and-operator.md
Labels: Beginner, SWOC 2023

#105 Palindrome checker using recursion in C++ added
  C++/Recursion/Palindrome checker.md
Labels: Beginner, SWOC 2023

#107 Create Media Queries CSS
  CSS/Media Queries.md
Labels: Beginner, SWOC 2023

#118 Create Radix_Sort.md
  Algorithms/Radix Sort/Radix_Sort.md
Labels: Beginner, SWOC 2023

#122 Insertion Sort using recursion in C++ added
  C++/Recursion/Insertion sort.md
Labels: Beginner, SWOC 2023

#123 Update the content
  Algorithms/Selection Sort/selection-sort.md
Labels: Beginner, SWOC 2023

#119 Create Selection_Sort.md
  Algorithms/Selection Sort/Selection_Sort.md
Labels: Beginner, SWOC 2023

#125 Adding both Topological sort approaches (added in the folder algorithms/topological_sort/)
  Algorithms/Topological Sort/Topological_sort_dfs.cpp
  Algorithms/Topological Sort/Topological_sort_using_bfs.cpp
Labels: Medium, SWOC 2023

#128 Factorial in C++ using recursion added
  C++/Recursion/Factorial.md
Labels: Beginner, SWOC 2023

#138 Created React JSX Introduction
  React/React JSX Introduction.md
Labels: Medium, SWOC 2023

#135 JavaScript Event Handling Documentation
  Javascript/JavascriptEventHandling.md
Labels: Medium, SWOC 2023

#133 Reverse of a string using recursion in C++ added
  C++/Recursion/Reverse of a string.md
Labels: Beginner, SWOC 2023

#129 Bucketsort Documentation
  Algorithms/Bucket Sort/BucketSort.md
Labels: Beginner, SWOC 2023

#142 Added Introduction to HTML
  Html/Introduction to HTML.md
Labels: Beginner, SWOC 2023

#139 Added While loop documentation
  C++/Loops/While.md
Labels: Beginner, SWOC 2023

#144 Add Shell Sort
  Algorithms/Shell Sort/Shell Sort.md
Labels: Beginner, SWOC 2023

#153 Added for-loop documentation
  C++/Loops/for-loop.md
Labels: Beginner, SWOC 2023

#147 Added STL MAPS #127
  C++/C++ STL/STL Maps.md
Labels: Medium, SWOC 2023

#150 0/1 knap sack explanation
  Algorithms/Knapsack/ZeroOneKnapsack.md
Labels: Medium, SWOC 2023

#155 Added CSS Documentation
  CSS/Introduction-to-CCSS.md
  CSS/box-model.png
Labels: Beginner, SWOC 2023

#151 Added everyting from issue 101
  Html/Readme.md
  Html/style1.png
Labels: Beginner, SWOC 2023

#154 Bellman Ford Algorithm
  Algorithms/Bellman Ford/BellmanFord.cpp
  Algorithms/Bellman Ford/README.md
Labels: Medium, SWOC 2023

#131 Add Sieve of Eratosthenes Algorithm
  C++/Sieve of Eratosthenes/Sieve_of_eratosthenes.cpp
Labels: Beginner, SWOC 2023

#124 Update the Content
  Algorithms/Quick Sort/README.md
Labels: Beginner, SWOC 2023

#167 Added Dijkstra's Algorithm
  Algorithms/Dijkstras Algorithm/Dijkstras Algorithm.md
  Algorithms/Dijkstras Algorithm/Dijkstras.c
Labels: SWOC 2023

#168 Added Prims Algorithm
  Algorithms/Prims Algorithm/Prims Algoritm.md
  Algorithms/Prims Algorithm/PrimsAlgorithm.cpp
Labels: Medium, SWOC 2023

#180 Gnome Sorting Algorithm
  Algorithms/Gnome Sort/Gnome_Sorting.java
  Algorithms/Gnome Sort/Gnome_sort.cpp
  Algorithms/Gnome Sort/README.md
Labels: Beginner, SWOC 2023

#175 Binary Tree Traversals Using Stacks
  C++/Binary Tree Stack Traversals/Traversals_Using_Stack.cpp
Labels: Beginner, SWOC 2023

#183 JavaScript Array Methods Documentation
  Javascript/JavascriptArrayMethod.md
Labels: Beginner, SWOC 2023

#186 Added KMP Algorithm documentation
  Algorithms/KMP Algorithm/KMP_Algorithm.cpp
  Algorithms/KMP Algorithm/KMP_Algorithm.md
Labels: Beginner, SWOC 2023

#187 Add React Component and State
  React/React Component and State.md
Labels: Beginner, SWOC 2023

#188 Introduction of Kubernetes
  Kubernetes/Introduction of Kubernetes.md
Labels: Medium, SWOC 2023

#182 Banker Algorithm Operating System
  Algorithms/Banker Algorithm/Banker_Algorithm.cpp
Labels: Beginner, SWOC 2023

#172 Hare & Tortoise algorithm
  Algorithms/Hare & Tortoise algorithm/Hare&Tortoisealgorithm.md
  Algorithms/Hare & Tortoise algorithm/code.cpp
Labels: Medium, SWOC 2023

#169 Multistage graph Documentation
  Algorithms/Multistage Graph/Multistage Graph.md
Labels: Beginner, SWOC 2023

#181 Best Fit Algorithm Operating System
  Algorithms/Best Fit/BestFit.cpp
Labels: Beginner, SWOC 2023

#190 Adding Binary Searching Algorithm in the Algorithms folder #164
  Algorithms/Linear Search/LinearSearch.md
Labels: Beginner, SWOC 2023

#189 Exception Handling in C++ | Issue #178
  C++/Exception Handling/Exception Handling.md
Labels: Beginner, SWOC 2023
